version: "3.8"

services:
  backend:
    image: loadresourcetest:latest
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 5000:80
  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
